# Generated by Django 6.0.5 on 2026-07-20 14:49

import inventario.models.producto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=inventario.models.producto.product_image_path),
        ),
    ]
