# Generated by Django 6.0.5 on 2026-06-04 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.proveedor', verbose_name='Proveedor'),
        ),
    ]
