# Generated by Django 5.2.6 on 2026-06-26 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_movimientoinventario_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ajuste', models.CharField(choices=[('ROBO', 'Robo o Hurto'), ('DANO', 'Mercadería Dañada/Rota'), ('CADUCIDAD', 'Caducidad/Vencimiento'), ('ERROR', 'Error de Conteo')], max_length=15)),
                ('cantidad', models.IntegerField(help_text='Usa negativos para disminuir stock, positivos para aumentar')),
                ('justificativo', models.TextField(verbose_name='Descripción o motivo legal')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='inventario.producto')),
            ],
            options={
                'db_table': 'inventario_ajuste_inventario',
                'ordering': ['-creado_en'],
            },
        ),
    ]
