# Generated by Django 5.2.6 on 2026-06-26 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_ajusteinventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_serial', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie / IMEI')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('VENDIDO', 'Vendido'), ('DANO', 'Dañado')], default='DISPONIBLE', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_serie', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Número de Serie',
                'verbose_name_plural': 'Números de Serie',
                'db_table': 'inventario_numero_serie',
            },
        ),
    ]
