# Generated by Django 5.2.6 on 2026-06-26 19:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_numeroserie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio de Venta'),
        ),
        migrations.CreateModel(
            name='AlertaStockMinimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_minima', models.IntegerField(default=5, verbose_name='Stock Mínimo para Alerta')),
                ('email_notificacion', models.EmailField(max_length=254, verbose_name='Correo para compras')),
                ('activa', models.BooleanField(default=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alerta_stock', to='inventario.producto')),
            ],
            options={
                'db_table': 'inventario_alerta_stock',
            },
        ),
    ]
