# Generated by Django 5.2.6 on 2026-06-26 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_producto_precio_alertastockminimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(verbose_name='Motivo de la devolución')),
                ('cantidad', models.IntegerField(default=1)),
                ('estado_producto', models.CharField(choices=[('BUENO', 'Buen Estado'), ('DANO', 'Dañado'), ('USADO', 'Usado')], default='BUENO', max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Devolución de Cliente',
                'verbose_name_plural': 'Devoluciones de Clientes',
                'db_table': 'inventario_devolucion_cliente',
            },
        ),
    ]
